resources:
  - repo: self
pool:
  name: Hosted
steps:
  - task: AzureResourceGroupDeployment@2
    displayName: >-
      Azure Deployment: Deploy API Named Values
    inputs:
      azureSubscription: AzureLogistics
      csmFile: ./template/apim-int-deloitte-master.template.json
      csmParametersFile: ./template/apim-int-deloitte-parameters.json
      location: westeurope
      resourceGroupName: AzureLogistics-dev