resources:
  - repo: self
pool:
  name: Hosted
steps:
  - task: AzureResourceGroupDeployment@2
    displayName: >-
      Azure Deployment: Deploy APIM
    inputs:
      azureSubscription: AzureLogistics
      csmFile: ./templates/apim-int-deloitte-master.template.json
      csmParametersFile: ./templates/apim-int-deloitte-parameters.json
      location: westeurope
      resourceGroupName: AzureLogistics-dev